/*! ****************************************************************************
 * ES6Pakket v1.0.9x
 *
 * A boilerplate for building Javascript ES6 libraries with Pakket.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2023 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from {{boiler:name}} v{{boiler:name:version}}.
 * ************************************************************************** */
!/*! Generated by Pakket v1.0.7 */
const $__ES6GLOB={};(function(t,e){"use strict";if(typeof define==="function"&&define.amd){define([""],e)}else if(typeof exports==="object"){module.exports=e(t)}else{t.ES6Pakket=e(t)}})($__ES6GLOB,(t=>{"use strict";return function(){function t(e,n,r){function o(i){function u(t){const n=e[i][2][t];return o(n||t)}if(!n[i]){if(!e[i]){throw new Error(`Cannot find module "${i}"`)}n[i]={exports:{}};const o=n[i];e[i][1].call(o.exports,u,o,o.exports,t,e,n,r)}return n[i].exports}for(let t=0;t<r.length;t++){o(r[t])}return o}return t}()({1:["./src/prototypal",function(e,n,r){const o=e("./util/util");const i=t.ES6Pakket;let u;const c=function(){const t=Object.create(u);t._library={name:"ES6Pakket",version:"1.0.9x"};return t};c.NAME="ES6Pakket";c.VERSION="1.0.9x";c._setTestMode=function(){return[]};c.noConflict=function(){t.ES6Pakket=i;return this};u={whoami(){return this._library},getString(){return o.getString()},getArray(){return o.getArray()}};n.exports=c},{"./util/util":2}],2:["./src/util/util",function(t,e,n){function r(){return"I am a string!"}function o(){return[1,2,3]}const i={getString(){return r()},getArray(){return o()}};e.exports=i},{}]},{},[1])(1)}));export default $__ES6GLOB.ES6Pakket;