/*! ****************************************************************************
 * ES6Pakket v2.1.0
 *
 * A boilerplate for building Javascript ES6 libraries with Pakket.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2024 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from {{boiler:name}} v{{boiler:name:version}}.
 * ************************************************************************** */
/*! Generated by Pakket v1.2.0 */
const $__ES6GLOB={};!function(t,e){"use strict";"function"==typeof define&&define.amd?define([""],e):"object"==typeof exports?module.exports=e(t):t.ES6Pakket=e(t)}($__ES6GLOB,(t=>{"use strict";return function t(e,r,n){function o(i){function u(t){return o(e[i][2][t]||t)}if(!r[i]){if(!e[i])throw new Error(`Cannot find module "${i}"`);r[i]={exports:{}};const o=r[i];e[i][1].call(o.exports,u,o,o.exports,t,e,r,n)}return r[i].exports}for(let t=0;t<n.length;t++)o(n[t]);return o}({1:["./src/prototypal",function(e,r,n){const o=e("./util/util"),i=t.ES6Pakket;let u;const s=function(){const t=Object.create(u);return t._library={name:"ES6Pakket",version:"2.1.0"},t};s.NAME="ES6Pakket",s.VERSION="2.1.0",s._setTestMode=function(){return[]},s.noConflict=function(){return t.ES6Pakket=i,this},u={whoami(){return this._library},getString:()=>o.getString(),getArray:()=>o.getArray()},r.exports=s},{"./util/util":2}],2:["./src/util/util",function(t,e,r){const n={getString:()=>"I am a string!",getArray:()=>[1,2,3]};e.exports=n},{}]},{},[1])(1)}));export default $__ES6GLOB.ES6Pakket;