/*! ****************************************************************************
 * ES6Pakket v0.0.3-beta.6
 *
 * A boilerplate for building Javascript ES6 libraries with Pakket.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2020 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from {{boiler:name}} v{{boiler:name:version}}.
 * ************************************************************************** */
/*! Generated by Pakket v0.0.2-beta.4 */
const $__ES6GLOB={};!function(t,e){"use strict";"function"==typeof define&&define.amd?define([""],e):"object"==typeof exports?module.exports=e(t):t.ES6Pakket=e(t)}($__ES6GLOB,t=>{"use strict";return function t(e,n,r){function o(i){function u(t){return o(e[i][2][t]||t)}if(!n[i]){if(!e[i])throw new Error(`Cannot find module "${i}"`);n[i]={exports:{}};const o=n[i];e[i][1].call(o.exports,u,o,o.exports,t,e,n,r)}return n[i].exports}for(let t=0;t<r.length;t++)o(r[t]);return o}({1:["./src/prototypal",function(e,n,r){const o=e("./util/util"),i=t.ES6Pakket;let u;const s=function(t){const e=Object.create(u);return e._library={name:"ES6Pakket",version:"0.0.3-beta.6"},e.name=t,e};s.NAME="ES6Pakket",s.VERSION="0.0.3-beta.6",s._setTestMode=function(){return[]},s.noConflict=function(){return t.ES6Pakket=i,this},u={whoami(){return this._library},getString:()=>o.getString(),getArray:()=>o.getArray()},n.exports=s},{"./util/util":2}],2:["./src/util/util",function(t,e,n){const r={getString:()=>"I am a string!",getArray:()=>[1,2,3]};e.exports=r},{}]},{},[1])(1)});export default $__ES6GLOB.ES6Pakket;